import Head from "next/head";

import DefaultLayout from "@/components/default-layout";
import LinkBackHome from "@/components/layout/LinkBackHome";
import AllProjectBody from "@/components/pages/projects/AllProjectBody";
import EllipseShapeLandingTwoBottomRight from "@/components/layout/EllipseShapeLandingTwoBottomRight";
import AfterEffect from "@/components/layout/AfterEffect";


export default function Projects() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <LinkBackHome />
        <AllProjectBody />
      </div>
      <div className="about-top-left-element"></div>
      <AfterEffect />
      <EllipseShapeLandingTwoBottomRight />
    </>
  );
}
Projects.getLayout = function getLayout(page) {
  return (
    <DefaultLayout>
      {page}
    </DefaultLayout>
  )
}
